### ISSUE TITLE
Incompatible pixel format 'yuv420p10le' for codec 'hevc_nvenc'

### ISSUE THREAD

**Issue by trithucxx** [alxTools/video_resizer#1]
I'm using windows 10 launch your took but get error here: 

`Incompatible pixel format 'yuv420p10le' for codec 'hevc_nvenc', auto-selecting format 'p010le'
Stream mapping:
  Stream #0:0 -> #0:0 (h264 (native) -> hevc (hevc_nvenc))
  Stream #0:1 -> #0:1 (aac (native) -> aac (native))
Press [q] to stop, [?] for help
Impossible to convert between the formats supported by the filter 'graph 0 input from stream 0:0' and the filter 'auto_scale_0'
[vf#0:0 @ 000002854b05b000] Error reinitializing filters!
Failed to inject frame into filter network: Function not implemented
Error while filtering: Function not implemented
[out#0/mp4 @ 000002854b0d1340] Nothing was written into output file, because at least one of its streams received no packets.
frame=    0 fps=0.0 q=0.0 Lsize=       0kB time=00:00:00.53 bitrate=   0.0kbits/s speed=3.59x    
[aac @ 000002854b59dc40] Qavg: 10185.668
Conversion failed!
Conversion Completed!`

I upgrade newest FFmpeg, So how can I fix it.

**Comment by alxTools** [comment]
ok, i will check today for this! thanks bro

**Comment by alxTools** [comment]
> I'm using windows 10 launch your took but get error here:
> 
> `Incompatible pixel format 'yuv420p10le' for codec 'hevc_nvenc', auto-selecting format 'p010le' Stream mapping: Stream #0:0 -> #0:0 (h264 (native) -> hevc (hevc_nvenc)) Stream #0:1 -> #0:1 (aac (native) -> aac (native)) Press [q] to stop, [?] for help Impossible to convert between the formats supported by the filter 'graph 0 input from stream 0:0' and the filter 'auto_scale_0' [vf#0:0 @ 000002854b05b000] Error reinitializing filters! Failed to inject frame into filter network: Function not implemented Error while filtering: Function not implemented [out#0/mp4 @ 000002854b0d1340] Nothing was written into output file, because at least one of its streams received no packets. frame= 0 fps=0.0 q=0.0 Lsize= 0kB time=00:00:00.53 bitrate= 0.0kbits/s speed=3.59x [aac @ 000002854b59dc40] Qavg: 10185.668 Conversion failed! Conversion Completed!`
> 
> I upgrade newest FFmpeg, So how can I fix it.

so after you export your video_ai_processed_video in prores format and then when importing the video to the video-resizer-tool it raised an error because apparently hevc_nvenc codec for the yuv420 format is not working. can you please send me a capture of the tools-settings 
![image](https://github.com/alxTools/video_resizer/assets/40523587/b341d32d-9f83-44b8-83b9-42c7e79272e4)
